name: Release

on:
  workflow_dispatch:
  workflow_call:

concurrency: ${{ github.workflow }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - name: Publish to npm
        run: yarn changeset publish
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
