name: build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - run: yarn install --immutable
    - run: cargo fetch --locked
    - run: yarn build
    - run: yarn test
    - run: yarn lint
    - run: yarn fmt:check
