name: build and test (Rust)

on:
  push:
    branches:
    - master
  # Only when Rust-related files are updated
  pull_request:
    paths:
    - 'Cargo.toml'
    - 'Cargo.lock'
    - '**/Cargo.toml'
    - '**.rs'
    - '.github/workflows/test-rust.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Rust
      run: |
        rustup set profile minimal
        rustup install stable
        rustup component add rustfmt clippy
        rustup target add wasm32-unknown-unknown
    - run: cargo fetch --locked
    - run: cargo build -p swc-plugin-node-cjs-interop --target wasm32-unknown-unknown
    - run: cargo test --all
    - run: cargo clippy --all
    - run: cargo fmt --all --check
